[[breaking]]
title = ""
description = ""

[[features]]
title = "New resource"
description = "`oxide_silo` [#425](https://github.com/oxidecomputer/terraform-provider-oxide/pull/425)."

[[enhancements]]
title = ""
description = ""

[[bugs]]
title = ""
description = ""
